// Datos para la sección de Proyectos (comentados en el código original)
export const proyectos = [
  {
    title: "JR Cincelados",
    description:
      "Sitio web para taller artesanal especializado en productos de cuero hechos a mano en San Juanito de Escobedo. Incluye catálogo de productos, información del taller y servicios de personalización.",
    technologies: [
      "Next.js",
      "Tailwind CSS",
      "Optimización de imágenes WebP",
      "Aceternity",
    ],
    urlImage: "/proyects/jrcincelados.webp",
    type: "Completado",
    urlPage: "https://jrcincelados.com/",
    urlImageMobile: "/proyects/jrcincelados-mobile.webp",
    features: [
      "Diseño responsivo optimizado",
      "Catálogo de productos interactivo",
      "Galería de imágenes con lazy loading",
      "Integración con redes sociales (TikTok)",
      "Sección de testimonios",
      "Formulario de contacto directo",
      "Optimización SEO",
      "Imágenes en formato WebP para mejor rendimiento",
      "Diseño enfocado en artesanía tradicional",
    ],
  },
  {
    title: "PianoLab",
    description:
      "Landing page para programa de enseñanza de piano en línea dirigido a adultos principiantes. Presenta el método de aprendizaje de Dany Sánchez, con más de 10 años de experiencia, enfocado en resultados prácticos y acompañamiento personalizado.",
    technologies: [
      "Astro",
      "Tailwind CSS",
      "Flowbite",
      "Calendly Integration",
      "DiceBear Avatars API",
      "Vercel",
    ],
    urlImage: "/proyects/pianolab.webp",
    urlImageMobile: "/proyects/pianolab-mobile.webp",
    type: "Completado",
    urlPage: "https://pianolab.art/",
    features: [
      "Diseño responsivo tipo landing page de alta conversión",
      "Integración con Calendly para agendar llamadas gratuitas",
      "Sección de propuesta de valor con segmentación clara (para quién es / no es)",
      "Programa estructurado con 6 pilares del curso",
      "Sección de testimoniales con avatares dinámicos (DiceBear API)",
      "Página sobre la profesora con métricas de credibilidad",
      "FAQs para resolver objeciones de compra",
      "Integración con redes sociales (TikTok, Instagram, YouTube)",
      "Imágenes en formato WebP para mejor rendimiento",
      "Optimización SEO con meta tags y Open Graph",
      "CTA múltiples estratégicamente ubicados a lo largo de la página",
    ],
  },
  // {
  //   title: "Central Molletes",
  //   description: "Sitio web multi-página para cafetería establecida en Etzatlán, Jalisco desde 2020. Incluye menú digital por categorías, múltiples ubicaciones, blog, sección de nosotros y contacto. Imágenes gestionadas desde Cloudinary con un diseño editorial moderno enfocado en la experiencia gastronómica local.",
  //   technologies: ["Next.js", "Tailwind CSS", "Cloudinary", "Vercel", "Next Image Optimization"],
  //   urlImage: "/proyects/centralmolletes.webp",
  //   urlImageMobile: "/proyects/centralmolletes-mobile.webp",
  //   type: "Completado",
  //   urlPage: "https://centralmolletes.vercel.app/",
  //   features: [
  //       "Diseño responsivo multi-página (Home, Menú, Ubicaciones, Nosotros, Blog, Contacto)",
  //       "Catálogo de menú con 15 categorías filtrables",
  //       "Gestión de imágenes con Cloudinary",
  //       "Sección de promociones y descuentos dinámicos",
  //       "Páginas de detalle por producto del menú",
  //       "Sección de ubicaciones con horarios y dirección",
  //       "Blog integrado",
  //       "Sección de testimoniales de clientes reales",
  //       "Ticker animado con especialidades del menú",
  //       "Integración con redes sociales (Instagram, Facebook)",
  //       "Optimización SEO con meta tags, Open Graph y Twitter Cards",
  //       "Panel de login para personal autorizado",
  //       "Páginas legales (términos y privacidad)",
  //       "Diseño editorial con tipografía display de alto impacto"
  //   ]
  // },
  {
    title: "Mybeat",
    description:
      "Diario deportivo para corredores, ciclistas y caminantes que registra métricas mediante archivos GPX. Permite compartir el progreso con amigos o profesionales de la salud a través de un perfil público, destacando por su privacidad geográfica al proteger las rutas exactas del usuario.",
    technologies: ["Next.js", "Tailwind CSS", "Vercel"],
    urlImage: "/proyects/mybeat.webp",
    urlImageMobile: "/proyects/mybeat-mobile.webp",
    type: "Completado",
    urlPage: "https://www.mybeat.me/",
    features: [
      "Carga y procesamiento de archivos GPX (hasta 8 MB)",
      "Visualización de métricas deportivas: distancia, ritmo, duración, elevación y parciales",
      "Mapa interactivo con trazo de ruta GPS",
      "Control granular de privacidad por actividad (mapa, ritmo, frecuencia cardíaca, calorías)",
      "Perfil público compartible por username",
      "Búsqueda de perfiles públicos por username exacto (sin directorio ni sugerencias)",
      "Dashboard personal con historial de actividades",
      "Guía integrada para exportar GPX desde Strava, Garmin y Adidas Running",
      "Soporte para métricas de sensores: frecuencia cardíaca y cadencia cuando están en el GPX",
      "Optimización SEO con meta tags, Open Graph y Twitter Cards",
      "Páginas legales (política de privacidad y condiciones del servicio)",
      "Diseño responsivo con enfoque en salud y deporte",
    ],
  },
  {
    title: "LyriCLI",
    description:
      "Herramienta de línea de comandos open source escrita en Python que detecta automáticamente la canción que estás escuchando y muestra sus letras sincronizadas en tiempo real directamente en la terminal. Compatible con Windows (via Windows Media Session) y Linux (via MPRIS). Sin interfaces gráficas ni configuración extra.",
    technologies: [
      "Python",
      "Rich",
      "pyfiglet",
      "lrclib.net API",
      "MPRIS",
      "Windows Media Session",
      "Vercel",
    ],
    urlImage: "/proyects/lyricli.webp",
    urlImageMobile: "/proyects/lyricli-mobile.webp",
    type: "Completado",
    urlPage: "https://lyricli.vercel.app/",
    features: [
      "Auto-detección de la canción en reproducción sin configuración adicional",
      "Letras sincronizadas en tiempo real usando el formato LRC con timestamps precisos",
      "Integración con lrclib.net para obtener letras de cualquier canción",
      "Compatibilidad con Windows Media Session y MPRIS en Linux",
      "Detección automática de cambio de canción sin reiniciar el proceso",
      "Renderizado en terminal con Rich: tipografía grande, colores neón y efecto glitch",
      "Modo manual con flags --artist y --title para búsqueda directa",
      "Soporte para Python 3.8+",
      "Compatible con Spotify y cualquier reproductor de música",
      "Instalación sencilla vía pip y git clone",
      "Licencia MIT · Open Source en GitHub",
      "Landing page con documentación de instalación paso a paso para Windows y Linux",
    ],
  },
];
